---

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/BlockLength:
  Exclude:
    - fluent-plugin-syscheck.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false
